# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger: none

strategy:
  matrix:
    black-ubuntu:
      pyver: 3.9
      toxArg: black
      vmImage: ubuntu-20.04
    black-windows:
      pyver: 3.9
      toxArg: black
      vmImage: windows-2019
    flake8-ubuntu:
      pyver: 3.9
      toxArg: flake8
      vmImage: ubuntu-20.04
    flake8-windows:
      pyver: 3.9
      toxArg: flake8
      vmImage: windows-2019
    py38-ubuntu:
      pyver: 3.8
      toxArg: py38
      vmImage: ubuntu-20.04
    py38-windows:
      pyver: 3.8
      toxArg: py38
      vmImage: windows-2019
    py39-ubuntu:
      pyver: 3.9
      toxArg: py39
      vmImage: ubuntu-20.04
    py39-windows:
      pyver: 3.9
      toxArg: py39
      vmImage: windows-2019
    py310-ubuntu:
      pyver: 3.10
      toxArg: py310
      vmImage: ubuntu-20.04
    py310-windows:
      pyver: 3.10
      toxArg: py310
      vmImage: windows-2019

pool:
  vmImage: $ (vmImage)

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(pyver)'
    addToPath: true

- script: pip install tox
  displayName: 'Install tox'

- script: tox -e $(toxArg)
  displayName: 'Run $(toxArg)'

# TODO: 1. Install Python 3.10 in this system and run tox for it. (NOT doing)
# 2. Try using pytest parallel and pytest cov with the appropriate packages.
# 3. Output test results in terminal as well as xml output files.
# 4. Make the required changes to README and Azure pipelines to run tests
# in cross-platform environments. 