trigger:
- main

strategy:
  matrix:
    black-ubuntu:
      pyver: 3.9
      toxArg: black
      vmImage: ubuntu-20.04
    black-windows:
      pyver: 3.9
      toxArg: black
      vmImage: windows-2019
    flake8-ubuntu:
      pyver: 3.9
      toxArg: flake8
      vmImage: ubuntu-20.04
    flake8-windows:
      pyver: 3.9
      toxArg: flake8
      vmImage: windows-2019
    py38-ubuntu:
      pyver: 3.8
      toxArg: py38
      vmImage: ubuntu-20.04
    py38-windows:
      pyver: 3.8
      toxArg: py38
      vmImage: windows-2019
    py39-ubuntu:
      pyver: 3.9
      toxArg: py39
      vmImage: ubuntu-20.04
    py39-windows:
      pyver: 3.9
      toxArg: py39
      vmImage: windows-2019
    py310-ubuntu:
      pyver: 3.10
      toxArg: py310
      vmImage: ubuntu-20.04
    py310-windows:
      pyver: 3.10
      toxArg: py310
      vmImage: windows-2019

pool:
  vmImage: $(vmImage)

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(pyver)'
    addToPath: true

- script: pip install tox
  displayName: 'Install tox'

- script: tox -e $(toxArg)
  displayName: 'Run $(toxArg)'
 